services:
  web:
    build:
      context: ./apps/web/
      dockerfile: Dockerfile
      args:
        VITE_CLERK_PUBLISHABLE_KEY: ${CLERK_PUBLISHABLE_KEY}
    restart: always
    depends_on:
      - api
    networks:
      - frontend
    ports:
      - 8080

  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    environment:
      - CLERK_PUBLISHABLE_KEY=${CLERK_PUBLISHABLE_KEY}
      - CLERK_SECRET_KEY=${CLERK_SECRET_KEY}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    restart: always
    depends_on:
      - redis
    networks:
      - backend
      - frontend

  redis:
    image: "redis:latest"
    ports:
      - "6379"
    networks:
      - backend
    volumes:
      - cache:/data

networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge

volumes:
  postgres_data:
    driver: local
    driver_opts:
      type: none
      device: ./pgdata
      o: bind
  cache:
    driver: local
