services:
  web:
    build:
      context: ./apps/web/
      dockerfile: Dockerfile
    environment:
      - CLERK_PUBLISHABLE_KEY=${CLERK_PUBLISHABLE_KEY}
      - VITE_CLERK_PUBLISHABLE_KEY=${CLERK_PUBLISHABLE_KEY}
      - CLERK_SECRET_KEY=${CLERK_SECRET_KEY}
    restart: always
    depends_on:
      - api
    networks:
      - frontend
    ports:
      - 8080
    expose: 
      - 8080

  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    environment:
      - CLERK_PUBLISHABLE_KEY=${CLERK_PUBLISHABLE_KEY}
      - CLERK_SECRET_KEY=${CLERK_SECRET_KEY}
    restart: always
    networks:
      - backend
      - frontend

networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge

volumes:
  postgres_data:
    driver: local
    driver_opts:
      type: none
      device: ./pgdata
      o: bind

