/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HelloPageRouteImport } from './routes/HelloPage'
import { Route as IndexRouteImport } from './routes/index'

const HelloPageRoute = HelloPageRouteImport.update({
  id: '/HelloPage',
  path: '/HelloPage',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/HelloPage': typeof HelloPageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/HelloPage': typeof HelloPageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/HelloPage': typeof HelloPageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/HelloPage'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/HelloPage'
  id: '__root__' | '/' | '/HelloPage'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HelloPageRoute: typeof HelloPageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/HelloPage': {
      id: '/HelloPage'
      path: '/HelloPage'
      fullPath: '/HelloPage'
      preLoaderRoute: typeof HelloPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HelloPageRoute: HelloPageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
